### ISSUE TITLE
Always ConsentType.unknown

### ISSUE THREAD

**Issue by stoppiNeobiz** [blaugold/user_messaging_platform#11]
Hi, 
I'm testing the plugin, why it always gives me ConsentType.unknown?
Thanks.

**Comment by blaugold** [comment]
Hey @stoppiNeobiz. The plugin just passes through the `consentType` it gets from the UserMessagingPlatform SDK. For what its worth, I always get `ConsentType.unknown` in my apps, too. Maybe the [AdMob support](https://support.google.com/admob/) has more info.

**Comment by stoppiNeobiz** [comment]
hi @blaugold. Thanks for the quick response, so are we comfortable with regards to personalized ads? thanks

**Comment by blaugold** [comment]
Since the UMP SDK implements IAB TCF and because of that the users choices are encoded in the TC string, which is sent with each ad request, enabling personalized ads should be fine. It's up to the ad vendors to verify consent, based on the TC string.

**Comment by stoppiNeobiz** [comment]
perfect, I ask you one last question, I use mediations through admob, this consent I guess covers them too, right?

**Comment by blaugold** [comment]
You need to make sure that each SDK of the mediation partner supports IAB TCF. [Here](https://developers.google.com/admob/ump/android/quick-start#mediation) you can find the docs regarding the UMP SDK and mediation.

**Comment by blaugold** [comment]
Closing this since `ConsentType` API has been removed (028967acba9b5a205573078e22cf78b72ef7c761).
