### ISSUE TITLE
Swift compiler error

### ISSUE THREAD

**Issue by phanvanluan94** [blaugold/user_messaging_platform#13]
I cannot run up application with version 0.2.1 and got below error
<img width="501" alt="Screen Shot 2021-05-23 at 13 52 50" src="https://user-images.githubusercontent.com/22259333/119251012-3adab180-bbce-11eb-9ab0-bbdc71b6f829.png">

**Comment by blaugold** [comment]
@phanvanluan94 Thanks for reporting this. There was a breaking change in the Google UMP SDK. I'll have a fix this today probably.

**Comment by blaugold** [comment]
Version `1.0.0` has been published which includes a fix. 

Closed by cb90d3eb77af725ee55451085af1142557246f53 and 028967acba9b5a205573078e22cf78b72ef7c761.
