### ISSUE TITLE
App Icon loading error in consent form (Android)

### ISSUE THREAD

**Issue by GoldenSoju** [blaugold/user_messaging_platform#14]
Hi!

Thanks a lot for the package.

So far the implementation is working fine, the only problem is that my app icon doesn't show in the consent form.
The "image broken" placeholder appears instead.

My app icon is in XML format, so my guess is that it has to be in PNG maybe?
Do you maybe know how to display the icon without changing it to another format? Or is there another reason?

**Comment by blaugold** [comment]
This is not something this package has any control over, since it's just a Dart API for the UMP SDK. But I think your right that a different format probably will fix it. Vector graphics such as SVG are often not as well supported as simple bitmaps like PNG, JPEG, etc.
