### ISSUE TITLE
Please provide a way to test and force a geography

### ISSUE THREAD

**Issue by oliverbytes** [blaugold/user_messaging_platform#15]
Currently, there's no method to set/force the geography so we can test the form.

https://developers.google.com/admob/ump/android/quick-start#testing

- Kudos to the developer for this great package!

**Comment by blaugold** [comment]
Hey @nemoryoliver,

You can force the geography for testing like this:

```dart
UserMessagingPlatform.instance.requestConsentInfoUpdate(ConsentRequestParameters(
  debugSettings: ConsentDebugSettings(
    geography: DebugGeography.EEA,
  )
));
```

**Comment by oliverbytes** [comment]
Thank you
