### ISSUE TITLE
Kotlin Gradle Plugin Outdated

### ISSUE THREAD

**Issue by ghost** [blaugold/user_messaging_platform#17]
After upgrading flutter sdk to 2.10.1, I can't run because it says Kotlin is outdated for this package. 

In android/build.gradle, I changed ext.kotlin_version = '1.3.50'  -> '1.6.10' (latest version right now) and it works now. I believe this fixes the issue.

Thanks.

**Comment by blaugold** [comment]
This is now fixed in version `1.2.0`.
