### ISSUE TITLE
FormException(message: No available form can be built., code: FormErrorCode.invalidOperation)

### ISSUE THREAD

**Issue by samatzp** [blaugold/user_messaging_platform#18]
Hi!
Thanks for package!

I have with problem showing consent form

consentStatus = ConsentStatus.notRequired
formStatus = FormStatus.unavailable

Error: FormException(message: No available form can be built., code: FormErrorCode.invalidOperation)

**Comment by blaugold** [comment]
Hm, I don't think you can show a form when consent is not required.

But for testing and debugging, you can use `ConsentDebugSettings`:
```dart
await UserMessagingPlatform.instance.requestConsentInfoUpdate(
   ConsentRequestParameters(
       debugSettings : ConsentDebugSettings(
         geography: DebugGeography.EEA,
      ),
   ),
);
```
Also, see the docs for [ConsentDebugSettings.testDeviceIds](https://pub.dev/documentation/user_messaging_platform/latest/user_messaging_platform/ConsentDebugSettings/testDeviceIds.html).

**Comment by samatzp** [comment]
I tried without and with VPN

Below is the code that I am using:

```dart
try {
  var info = await UserMessagingPlatform.instance
      .requestConsentInfoUpdate(ConsentRequestParameters(
      debugSettings: ConsentDebugSettings(
geography: DebugGeography.EEA,
          testDeviceIds: ['MyDeviceId']
      )));
  print(info.consentStatus);
  print(info.formStatus);

  
  //error
  var test = await UserMessagingPlatform.instance.showConsentForm();

  print(test.consentStatus);
  print(test.formStatus);
}catch (err){
  print('Error tt');
  print(err);
}
```

**Comment by blaugold** [comment]
In that case, I'm not sure what's the problem. Just to make sure, did you configure messages in AdMob under Privacy & messaging?

**Comment by samatzp** [comment]
Yes

But Approval status is --> Getting ready
Could this affect?

<img width="1442" alt="google_admob_2022-03-11_19-49-45" src="https://user-images.githubusercontent.com/50781959/157922650-de904ba6-2fe0-4502-ab27-14eed4cc52f1.png">

![2022-03-11_21-54-42](https://user-images.githubusercontent.com/50781959/157923223-bad9eaa2-c4f0-42dd-b150-c45ae17fd927.png)

**Comment by samatzp** [comment]
Work after --> Approval status = Ready
Thanks!

**Comment by blaugold** [comment]
Thanks for the update! Glad it worked itself out.

**Comment by Quietly-20201113** [comment]
```dart
D/HwDragEnhancementImpl(21763): Start long press for hw drag enhancement.
D/WebViewDragEnhancement(21763): dragReset.
D/WebViewDragEnhancement(21763): dragReset cacheSize = 0
V/AudioManager(21763): querySoundEffectsEnabled...
I/AudioManager(21763): querySoundEffectsEnabled fail id: 0
W/UserMessagingPlatform(21763): No available form can be built.
E/flutter (21763): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormException(message: No available form can be built., code: FormErrorCode.invalidOperation)
E/flutter (21763): #0      UserMessagingPlatform.showConsentForm (package:user_messaging_platform/user_messaging_platform.dart:375:7)
E/flutter (21763): <asynchronous suspension>
E/flutter (21763): 
```
When I get an error using the official demo, how do I solve it?
