### ISSUE TITLE
Support consent request parameters

### ISSUE THREAD

**Issue by blaugold** [blaugold/user_messaging_platform#8]

**Comment by kaboc** [comment]
@blaugold 
This package looks very useful, so it is a pity that there is currently no way to show the GDPR consent dialog for testing outside EEA. When are you going to add the support for the parameters?

**Comment by blaugold** [comment]
Hey @kaboc, thanks for the feedback. I'll try to get to it today or tomorrow.

**Comment by kaboc** [comment]
Wow great! Looking forward to it. Thanks, @blaugold.

**Comment by blaugold** [comment]
This feature is now available in `v0.2.1`.

Closed by #12
